version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: db

  parser:
     image: imwisagist/codeforces_task_parser:v1.2
     restart: always
     depends_on:
       - db
     env_file:
       - .env
     container_name: parser

  bot:
    image: imwisagist/codeforces_bot:v1.2
    restart: always
    depends_on:
      - parser
    env_file:
      - .env
    container_name: bot

volumes:
  postgres_data:
